#!/usr/bin/env ruby
#
# Relink all pdfs
#
# Backup database before running this the first time.

# Load Rails environment
puts "Loading rails environment"

RAILS_ENV = "production"

require 'rubygems'
require 'active_record'

require 'config/environment'


puts "Starting to relink all files..."

# Relink all pdfs
Pdf.relink_all

