# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "pdfs", :force => true do |t|
    t.column "pdfdate",  :date
    t.column "pdfname",  :string
    t.column "filename", :string
    t.column "pdfnote",  :text
    t.column "cat_id",   :integer
  end

end
